import { PrismaClient } from '@prisma/client'
import { hashPassword } from '../src/lib/password'

const db = new PrismaClient()

async function main() {
  await db.$connect()
  const adminPasswordHash = await hashPassword('Puspa@2026')

  console.log('🌱 Seeding PUSPA NGO database...\n')

  // ============================================================
  // 1. ORGANIZATION PROFILE
  // ============================================================
  const org = await db.organizationProfile.create({
    data: {
      legalName: 'Pertubuhan Urus Peduli Asnaf',
      tradeName: 'PUSPA',
      registrationType: 'pertubuhan',
      registrationNumber: 'PPM-006-14-14032020',
      foundedDate: new Date('2020-03-14'),
      registeredAddress: 'No. 23, Jalan Hulu Klang 3, 54200 Kuala Lumpur',
      operatingAddress: 'No. 23, Jalan Hulu Klang 3, 54200 Kuala Lumpur',
      phone: '03-4107 8899',
      email: 'info@puspa.org.my',
      website: 'www.puspa.org.my',
      bankName: 'Maybank Islamic',
      bankAccount: '5621 7890 3456',
      bankVerified: true,
      lhdnApprovalRef: 'LHDN.01/35/42/179/2021',
      lhdnApprovalExpiry: new Date('2026-12-31'),
      isTaxExempt: true,
      missionStatement:
        'Memperkasa kebajikan asnaf melalui pengurusan berteraskan Islam dan profesional',
      visionStatement:
        'Menjadi NGO terkemuka dalam pengurusan asnaf yang telus dan berkesan',
    },
  })
  console.log(`✅ OrganizationProfile created: ${org.tradeName}`)

  // ============================================================
  // 2. ADMIN USER
  // ============================================================
  const admin = await db.user.upsert({
    where: { email: 'admin@puspa.org.my' },
    update: {
      password: adminPasswordHash,
      name: 'Pentadbir PUSPA',
      role: 'admin',
      phone: '03-4107 8899',
      isActive: true,
    },
    create: {
      email: 'admin@puspa.org.my',
      password: adminPasswordHash,
      name: 'Pentadbir PUSPA',
      role: 'admin',
      phone: '03-4107 8899',
      isActive: true,
    },
  })
  console.log(`✅ User created: ${admin.name} (${admin.role})`)

  // ============================================================
  // 3. BOARD MEMBERS
  // ============================================================
  const boardMembers = await db.boardMember.createMany({
    data: [
      {
        name: 'Haji Ahmad bin Ismail',
        title: 'Haji',
        role: 'chairman',
        appointmentDate: new Date('2022-01-15'),
        phone: '012-345 6789',
        email: 'ahmad.ismail@puspa.org.my',
        bio: 'Bekas pensyarah universiti dengan pengalaman 20 tahun dalam kerja amal',
        isCurrent: true,
      },
      {
        name: 'Dr. Siti Aminah binti Hassan',
        title: 'Dr.',
        role: 'adviser',
        appointmentDate: new Date('2020-03-14'),
        phone: '013-456 7890',
        email: 'siti.aminah@puspa.org.my',
        bio: 'Pakar pembangunan komuniti dan perunding NGO',
        isCurrent: true,
      },
      {
        name: 'Ustaz Muhammad bin Abdullah',
        title: 'Ustaz',
        role: 'deputy_chairman',
        appointmentDate: new Date('2023-03-01'),
        phone: '014-567 8901',
        email: 'muhammad.abdullah@puspa.org.my',
        bio: 'Graduan Universiti Al-Azhar, aktif dalam dakwah dan kebajikan',
        isCurrent: true,
      },
      {
        name: 'Puan Noraini binti Omar',
        title: 'Puan',
        role: 'treasurer',
        appointmentDate: new Date('2022-01-15'),
        phone: '016-678 9012',
        email: 'noraini.omar@puspa.org.my',
        bio: 'Akauntan berdaftar dengan pengalaman pengurusan kewangan NGO',
        isCurrent: true,
      },
      {
        name: 'Encik Kamal bin Zainal',
        title: 'Encik',
        role: 'secretary',
        appointmentDate: new Date('2023-03-01'),
        phone: '017-789 0123',
        email: 'kamal.zainal@puspa.org.my',
        bio: 'Pegawai kerajaan persaraan yang aktif dalam kerja sukarela',
        isCurrent: true,
      },
      {
        name: 'Puan Aishah binti Yusof',
        title: 'Puan',
        role: 'deputy_secretary',
        appointmentDate: new Date('2024-01-10'),
        phone: '018-890 1234',
        email: 'aishah.yusof@puspa.org.my',
        bio: 'Peguam belia yang berdedikasi dalam isu kebajikan sosial',
        isCurrent: true,
      },
      {
        name: 'Encik Rizal bin Hamid',
        title: 'Encik',
        role: 'committee',
        appointmentDate: new Date('2024-01-10'),
        phone: '019-901 2345',
        email: 'rizal.hamid@puspa.org.my',
        bio: 'Usahawan tempatan yang aktif dalam CSR komuniti',
        isCurrent: true,
      },
    ],
  })
  console.log(`✅ BoardMembers created: ${boardMembers.count} records`)

  // ============================================================
  // 4. PARTNERS
  // ============================================================
  const partners = await db.partner.createMany({
    data: [
      {
        name: 'Masjid Al-Ikhlas Hulu Klang',
        type: 'masjid',
        relationship: 'Rakan program kebajikan dan edaran zakat',
        contactPerson: 'Imam Haji Zulkifli',
        contactPhone: '03-4108 1234',
        address: 'Jalan Hulu Klang 1, 54200 Kuala Lumpur',
        verifiedStatus: 'partner_confirmed',
        notes: 'Rakan utama untuk program bantuan makanan',
      },
      {
        name: 'Masjid Jamek Ampang',
        type: 'masjid',
        relationship: 'Rakan edaran zakat fitrah',
        contactPerson: 'Ustaz Hamzah',
        contactPhone: '03-4296 5678',
        address: 'Jalan Besar Ampang, 68000 Ampang',
        verifiedStatus: 'partner_confirmed',
        notes: 'Titik edaran zakat utama kawasan Ampang',
      },
      {
        name: 'Masjid Al-Muttaqin Gombak',
        type: 'masjid',
        relationship: 'Rakan kempen pendidikan',
        contactPerson: 'Encik Mohd Faiz',
        contactPhone: '03-6189 9012',
        address: 'Jalan Gombak, 53100 Kuala Lumpur',
        verifiedStatus: 'claimed',
        notes: 'Bersama program tabung pendidikan anak asnaf',
      },
      {
        name: 'Masjid At-Taqwa Setapak',
        type: 'masjid',
        relationship: 'Rakan komuniti',
        contactPerson: 'Ustaz Ismail',
        contactPhone: '03-4022 3456',
        address: 'Jalan Setapak, 53200 Kuala Lumpur',
        verifiedStatus: 'partner_confirmed',
      },
      {
        name: 'Masjid Nurul Hidayah Keramat',
        type: 'masjid',
        relationship: 'Rakan program kesihatan',
        contactPerson: 'Encik Ahmad Razak',
        contactPhone: '03-4262 7890',
        address: 'Jalan Keramat, 54200 Kuala Lumpur',
        verifiedStatus: 'claimed',
        notes: 'Lokasi klinik kesihatan komuniti',
      },
      {
        name: 'Yayasan Hasanah',
        type: 'foundation',
        relationship: 'Penderma strategik dan rakan geran',
        contactPerson: 'Puan Siti Roziah',
        contactPhone: '03-2712 3456',
        contactEmail: 'partnership@yayasanhasanah.org',
        address: 'Level 15, Menara Yayasan Hasanah, KL',
        verifiedStatus: 'publicly_verified',
        verificationUrl: 'https://yayasanhasanah.org',
        notes: 'Penyedia geran utama untuk program pendidikan',
      },
      {
        name: 'Majlis Perbandaran Ampang',
        type: 'government',
        relationship: 'Rakan gotong-royong dan program komuniti',
        contactPerson: 'Encik Azmi bin Alias',
        contactPhone: '03-4292 1234',
        address: 'Jalan Pandan Indah, 55100 Ampang',
        verifiedStatus: 'publicly_verified',
        notes: 'Sokongan logistik untuk program komuniti',
      },
      {
        name: 'Kementerian Kesihatan Malaysia',
        type: 'government',
        relationship: 'Rakan program kesihatan komuniti',
        contactPerson: 'Dr. Lim Wei Ling',
        contactPhone: '03-8881 0200',
        contactEmail: 'program@kkm.gov.my',
        address: 'Kompleks KKM, Putrajaya',
        verifiedStatus: 'publicly_verified',
        notes: 'Sokongan perubatan dan nasihat untuk klinik komuniti',
      },
    ],
  })
  console.log(`✅ Partners created: ${partners.count} records`)

  // ============================================================
  // 5. MEMBERS (ASNAF) - 15 members with 3 having household members
  // ============================================================
  const membersData = [
    {
      memberNumber: 'PUSPA-0001',
      name: 'Fatimah binti Osman',
      ic: '620315-07-5452',
      phone: '012-987 6543',
      email: 'fatimah.osman@email.com',
      address: 'No. 5, Jalan 3/12, Taman Sri Hulu Klang',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '54200',
      householdSize: 4,
      monthlyIncome: 850,
      maritalStatus: 'widowed',
      occupation: 'Penjual kuih',
      status: 'active',
      notes: 'Janda dengan 3 orang anak. Layak bantuan zakat.',
    },
    {
      memberNumber: 'PUSPA-0002',
      name: 'Ahmad bin Razak',
      ic: '780422-01-5731',
      phone: '013-876 5432',
      address: 'Blok C, Flat Taman Melati',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '53100',
      householdSize: 5,
      monthlyIncome: 1200,
      maritalStatus: 'married',
      occupation: 'Pemandu teksi',
      bankAccount: '1142 3344 5566',
      bankName: 'Bank Islam',
      status: 'active',
      notes: 'Isi rumah besar. Anak dalam pendidikan.',
    },
    {
      memberNumber: 'PUSPA-0003',
      name: 'Zaiton binti Mamat',
      ic: '850610-10-5084',
      phone: '014-765 4321',
      address: 'No. 12, Jalan Mawar, Taman Ampang Indah',
      city: 'Ampang',
      state: 'Selangor',
      postalCode: '68000',
      householdSize: 2,
      monthlyIncome: 600,
      maritalStatus: 'divorced',
      occupation: 'Buruh sementara',
      status: 'active',
      notes: 'Penyakit kronik. Perlukan bantuan perubatan.',
    },
    {
      memberNumber: 'PUSPA-0004',
      name: 'Mohd Faisal bin Ismail',
      ic: '900501-01-6123',
      phone: '015-654 3210',
      address: 'No. 8, Lorong 5, Kampung Kuantan',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '51200',
      householdSize: 1,
      monthlyIncome: 450,
      maritalStatus: 'single',
      occupation: 'Penganggur',
      status: 'active',
      notes: 'Pemuda OKU. Layak program latihan kemahiran.',
    },
    {
      memberNumber: 'PUSPA-0005',
      name: 'Nurul Aini binti Abdullah',
      ic: '920815-03-5847',
      phone: '016-543 2109',
      address: 'No. 23, Jalan 1A, Taman Keramat',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '54200',
      householdSize: 3,
      monthlyIncome: 950,
      maritalStatus: 'married',
      occupation: 'Surirumah',
      bankAccount: '7623 4455 6677',
      bankName: 'Maybank Islamic',
      status: 'active',
      notes: 'Suami bekerja sebagai buruh binaan. Berpindah ke kawasan ini.',
    },
    {
      memberNumber: 'PUSPA-0006',
      name: 'Ismail bin Md Noor',
      ic: '600923-01-5234',
      phone: '017-432 1098',
      address: 'Blok A, Flat Sri Gombak',
      city: 'Gombak',
      state: 'Selangor',
      postalCode: '53100',
      householdSize: 6,
      monthlyIncome: 1800,
      maritalStatus: 'married',
      occupation: 'Peniaga kecil',
      status: 'active',
      notes: 'Terkesan pandemik. Perniagaan merosot.',
    },
    {
      memberNumber: 'PUSPA-0007',
      name: 'Aminah binti Hashim',
      ic: '700718-08-5678',
      phone: '018-321 0987',
      address: 'No. 15, Jalan 4/3, Setapak Jaya',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '53200',
      householdSize: 2,
      monthlyIncome: 500,
      maritalStatus: 'widowed',
      occupation: 'Pesara',
      status: 'active',
      notes: 'Warga emas tinggal bersama anak OKU.',
    },
    {
      memberNumber: 'PUSPA-0008',
      name: 'Raju a/l Supramaniam',
      ic: '881230-08-5199',
      phone: '019-210 9876',
      address: 'No. 9, Jalan Ehsan 3, Taman Ampang Hilir',
      city: 'Ampang',
      state: 'Selangor',
      postalCode: '55000',
      householdSize: 4,
      monthlyIncome: 1500,
      maritalStatus: 'married',
      occupation: 'Pekerja kilang',
      bankAccount: '3344 5566 7788',
      bankName: 'CIMB Islamic',
      status: 'active',
      notes: 'Muallaf baru. Layak bantuan pemulihan.',
    },
    {
      memberNumber: 'PUSPA-0009',
      name: 'Siti Hajar binti Kamal',
      ic: '950412-06-5432',
      phone: '011-109 8765',
      address: 'Blok D, Flat Taman Sri Rampai',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '53300',
      householdSize: 1,
      monthlyIncome: 0,
      maritalStatus: 'single',
      occupation: 'Pelajar universiti',
      status: 'active',
      notes: 'Pelajar IPT dari keluarga miskin. Layak tabung pendidikan.',
    },
    {
      memberNumber: 'PUSPA-0010',
      name: 'Osman bin Haji Ali',
      ic: '560615-01-5101',
      phone: '012-098 7654',
      address: 'No. 3, Jalan Bunus, Kampung Baru',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '50300',
      householdSize: 1,
      monthlyIncome: 350,
      maritalStatus: 'divorced',
      occupation: 'Pembersih',
      status: 'active',
      notes: 'Warga emas bersendirian. Layak bantuan makanan.',
    },
    {
      memberNumber: 'PUSPA-0011',
      name: 'Rosnah binti Ismail',
      ic: '800905-04-5678',
      phone: '013-987 6543',
      address: 'No. 7, Jalan 6, Taman Saga, Ampang',
      city: 'Ampang',
      state: 'Selangor',
      postalCode: '68000',
      householdSize: 5,
      monthlyIncome: 1100,
      maritalStatus: 'married',
      occupation: 'Penjual sayur',
      status: 'active',
      notes: 'Suami mengalami kemalangan. Pendapatan berkurangan.',
    },
    {
      memberNumber: 'PUSPA-0012',
      name: 'Khalid bin Mat Zin',
      ic: '930217-01-6321',
      phone: '014-876 5432',
      address: 'Blok B, PPR Gombak Setia',
      city: 'Gombak',
      state: 'Selangor',
      postalCode: '53100',
      householdSize: 2,
      monthlyIncome: 700,
      maritalStatus: 'single',
      occupation: 'Pekerja kedai runcit',
      status: 'active',
      notes: 'Menjaga ibu yang uzur.',
    },
    {
      memberNumber: 'PUSPA-0013',
      name: 'Halimah binti Sulaiman',
      ic: '750321-10-5456',
      phone: '015-765 4321',
      address: 'No. 21, Jalan 2/1, Taman Setapak Indah',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '53200',
      householdSize: 4,
      monthlyIncome: 900,
      maritalStatus: 'married',
      occupation: 'Surirumah',
      status: 'inactive',
      notes: 'Tidak aktif sejak berpindah ke negeri lain.',
    },
    {
      memberNumber: 'PUSPA-0014',
      name: 'Abdul Rahman bin Haji Omar',
      ic: '650830-01-5098',
      phone: '016-654 3210',
      address: 'No. 45, Jalan Hulu Kelang, Batu 8',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '53100',
      householdSize: 7,
      monthlyIncome: 2000,
      maritalStatus: 'married',
      occupation: 'Kontraktor kecil',
      bankAccount: '8899 0011 2233',
      bankName: 'Bank Rakyat',
      status: 'active',
      notes: 'Isi rumah ramai. Layak bantuan pendidikan untuk anak-anak.',
    },
    {
      memberNumber: 'PUSPA-0015',
      name: 'Mastura binti Yahya',
      ic: '880512-03-5789',
      phone: '017-543 2109',
      address: 'No. 11, Jalan 7/2, Taman Sri Keramat',
      city: 'Kuala Lumpur',
      state: 'Wilayah Persekutuan',
      postalCode: '54200',
      householdSize: 3,
      monthlyIncome: 750,
      maritalStatus: 'married',
      occupation: 'Penjaga kedai',
      status: 'active',
      notes: 'Anak bongsu memerlukan rawatan khas.',
    },
  ]

  const members = []
  for (const m of membersData) {
    members.push(await db.member.create({ data: m }))
  }
  console.log(`✅ Members created: ${members.length} records`)

  // 3 members with household members: PUSPA-0001, PUSPA-0002, PUSPA-0005
  const householdData: {
    name: string
    relationship: string
    age?: number
    occupation?: string
    income: number
    isOKU: boolean
    isStudent: boolean
    memberId: string
  }[] = [
    // PUSPA-0001: Fatimah (widowed, 4 household)
    {
      name: 'Nur Syafiqah binti Osman',
      relationship: 'child',
      age: 18,
      occupation: 'Pelajar Matrikulasi',
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[0].id,
    },
    {
      name: 'Muhammad Afiq bin Osman',
      relationship: 'child',
      age: 15,
      occupation: null,
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[0].id,
    },
    {
      name: 'Siti Aisyah binti Osman',
      relationship: 'child',
      age: 10,
      occupation: null,
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[0].id,
    },
    // PUSPA-0002: Ahmad Razak (married, 5 household)
    {
      name: 'Siti Khadijah binti Ahmad',
      relationship: 'spouse',
      age: 44,
      occupation: 'Surirumah',
      income: 0,
      isOKU: false,
      isStudent: false,
      memberId: members[1].id,
    },
    {
      name: 'Ahmad Farhan bin Ahmad Razak',
      relationship: 'child',
      age: 20,
      occupation: 'Pelajar Politeknik',
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[1].id,
    },
    {
      name: 'Nurul Izzah binti Ahmad Razak',
      relationship: 'child',
      age: 16,
      occupation: null,
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[1].id,
    },
    {
      name: 'Ahmad Hakim bin Ahmad Razak',
      relationship: 'child',
      age: 12,
      occupation: null,
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[1].id,
    },
    // PUSPA-0005: Nurul Aini (married, 3 household)
    {
      name: 'Aiman bin Zulkifli',
      relationship: 'spouse',
      age: 32,
      occupation: 'Buruh binaan',
      income: 950,
      isOKU: false,
      isStudent: false,
      memberId: members[4].id,
    },
    {
      name: 'Muhammad Aryan bin Aiman',
      relationship: 'child',
      age: 5,
      occupation: null,
      income: 0,
      isOKU: false,
      isStudent: true,
      memberId: members[4].id,
    },
  ]

  const householdMembers = await db.householdMember.createMany({
    data: householdData,
  })
  console.log(
    `✅ HouseholdMembers created: ${householdMembers.count} records`
  )

  // ============================================================
  // 6. PROGRAMMES - 8 programmes
  // ============================================================
  const programmesData = [
    {
      name: 'Program Bantuan Makanan Raya',
      description:
        'Pengedaran bungkusan makanan dan wang raya kepada asnaf sekitar Hulu Klang, Gombak dan Ampang sempena Hari Raya Aidilfitri.',
      category: 'food_aid',
      status: 'active',
      startDate: new Date('2024-03-01'),
      endDate: new Date('2024-04-10'),
      location: 'Masjid Al-Ikhlas Hulu Klang',
      targetBeneficiaries: 200,
      actualBeneficiaries: 178,
      budget: 25000,
      totalSpent: 22450,
      partners: 'Masjid Al-Ikhlas, Masjid Jamek Ampang',
    },
    {
      name: 'Tabung Pendidikan Anak Asnaf',
      description:
        'Tabung pendidikan untuk anak-anak asnaf dari sekolah rendah hingga IPT. Membantu yuran persekolahan, buku teks dan keperluan akademik.',
      category: 'education',
      status: 'active',
      startDate: new Date('2024-01-01'),
      endDate: new Date('2024-12-31'),
      location: 'Seluruh kawasan operasi PUSPA',
      targetBeneficiaries: 100,
      actualBeneficiaries: 67,
      budget: 50000,
      totalSpent: 33500,
      partners: 'Yayasan Hasanah, Masjid Al-Muttaqin Gombak',
    },
    {
      name: 'Latihan Kemahiran ICT',
      description:
        'Program latihan kemahiran komputer dan internet untuk asnaf dan belia dewasa bagi meningkatkan kebolehpasaran mereka.',
      category: 'skills_training',
      status: 'planned',
      startDate: new Date('2025-02-01'),
      endDate: new Date('2025-06-30'),
      location: 'Pusat Komuniti Hulu Klang',
      targetBeneficiaries: 50,
      actualBeneficiaries: 0,
      budget: 30000,
      totalSpent: 0,
      partners: 'Majlis Perbandaran Ampang',
    },
    {
      name: 'Klinik Kesihatan Komuniti',
      description:
        'Klinik kesihatan percuma bulanan untuk asnaf dan penduduk berpendapatan rendah. Pemeriksaan asas dan nasihat kesihatan.',
      category: 'healthcare',
      status: 'active',
      startDate: new Date('2023-06-01'),
      location: 'Masjid Nurul Hidayah Keramat',
      targetBeneficiaries: 300,
      actualBeneficiaries: 245,
      budget: 15000,
      totalSpent: 11200,
      partners: 'Kementerian Kesihatan Malaysia, Masjid Nurul Hidayah',
    },
    {
      name: 'Bantuan Kewangan Bulanan',
      description:
        'Bantuan kewangan bulanan tetap untuk asnaf terpilih yang memerlukan sokongan kewangan berterusan.',
      category: 'financial_assistance',
      status: 'active',
      startDate: new Date('2023-01-01'),
      endDate: new Date('2025-12-31'),
      location: 'Pejabat PUSPA',
      targetBeneficiaries: 80,
      actualBeneficiaries: 62,
      budget: 100000,
      totalSpent: 74400,
      notes: 'Bayaran RM100 sebulan setiap penerima',
    },
    {
      name: 'Gotong-Royong Komuniti',
      description:
        'Program gotong-royong membersih kawasan kediaman asnaf dan penduduk berpendapatan rendah bersama rakan komuniti.',
      category: 'community',
      status: 'completed',
      startDate: new Date('2024-05-15'),
      endDate: new Date('2024-05-15'),
      location: 'Taman Sri Hulu Klang',
      targetBeneficiaries: 100,
      actualBeneficiaries: 85,
      budget: 5000,
      totalSpent: 4800,
      partners: 'Majlis Perbandaran Ampang',
    },
    {
      name: 'Bantuan Mangsa Banjir',
      description:
        'Bantuan kecemasan kepada mangsa banjir di kawasan Hulu Klang dan Gombak termasuk makanan, pakaian dan barangan keperluan.',
      category: 'emergency_relief',
      status: 'suspended',
      startDate: new Date('2024-12-01'),
      endDate: new Date('2025-01-31'),
      location: 'Kawasan terjejas banjir Hulu Klang',
      targetBeneficiaries: 150,
      actualBeneficiaries: 42,
      budget: 20000,
      totalSpent: 8500,
      notes: 'Ditangguhkan kerana tiada kejadian banjir baharu. Dana disimpan sebagai simpanan kecemasan.',
    },
    {
      name: 'Kelas Dakwah Bulanan',
      description:
        'Kelas pengajian Islam dan dakwah bulanan untuk asnaf dan komuniti setempat.',
      category: 'dawah',
      status: 'active',
      startDate: new Date('2023-01-01'),
      location: 'Pejabat PUSPA & pelbagai masjid',
      targetBeneficiaries: 60,
      actualBeneficiaries: 48,
      budget: 8000,
      totalSpent: 5200,
      notes: 'Dianjurkan bersama ustaz jemputan dari pelbagai masjid',
    },
  ]

  const programmes = []
  for (const p of programmesData) {
    programmes.push(await db.programme.create({ data: p }))
  }
  console.log(`✅ Programmes created: ${programmes.length} records`)

  // ============================================================
  // 7. CASES - 15 cases across 12 statuses
  // ============================================================
  const caseStatuses = [
    'draft',
    'submitted',
    'verifying',
    'verified',
    'scoring',
    'scored',
    'approved',
    'disbursing',
    'disbursed',
    'follow_up',
    'closed',
    'rejected',
  ]

  const casesData = [
    {
      caseNumber: 'CS-0001',
      title: 'Bantuan zakat untuk keluarga Fatimah',
      description:
        'Permohonan bantuan zakat untuk janda dengan 3 anak di Hulu Klang. Perlu verifikasi pendapatan.',
      status: 'closed',
      priority: 'high',
      category: 'zakat',
      amount: 1500,
      memberId: members[0].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 85,
      welfareScore: 90,
      closedAt: new Date('2024-06-15'),
      createdAt: new Date('2024-03-01'),
    },
    {
      caseNumber: 'CS-0002',
      title: 'Bantuan pendidikan untuk Siti Hajar',
      description: 'Permohonan tabung pendidikan untuk pelajar universiti.',
      status: 'disbursed',
      priority: 'normal',
      category: 'sedekah',
      amount: 3000,
      memberId: members[8].id,
      programmeId: programmes[1].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 78,
      welfareScore: 82,
      createdAt: new Date('2024-04-10'),
    },
    {
      caseNumber: 'CS-0003',
      title: 'Bantuan perubatan Zaiton',
      description: 'Pesakit kronik memerlukan bantuan kos rawatan.',
      status: 'approved',
      priority: 'urgent',
      category: 'zakat',
      amount: 2000,
      memberId: members[2].id,
      programmeId: programmes[3].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 92,
      welfareScore: 95,
      createdAt: new Date('2024-05-20'),
    },
    {
      caseNumber: 'CS-0004',
      title: 'Bantuan bulanan Ismail bin Md Noor',
      description: 'Permohonan bantuan kewangan bulanan untuk peniaga kecil yang terkesan pandemik.',
      status: 'follow_up',
      priority: 'normal',
      category: 'zakat',
      amount: 1200,
      memberId: members[5].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 72,
      welfareScore: 75,
      createdAt: new Date('2024-06-01'),
    },
    {
      caseNumber: 'CS-0005',
      title: 'Latihan ICT untuk Mohd Faisal',
      description: 'Pemuda OKU memohon untuk menyertai program latihan kemahiran ICT.',
      status: 'scored',
      priority: 'high',
      category: 'sedekah',
      amount: 500,
      memberId: members[3].id,
      programmeId: programmes[2].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 88,
      welfareScore: 91,
      createdAt: new Date('2024-07-15'),
    },
    {
      caseNumber: 'CS-0006',
      title: 'Bantuan makanan raya Ahmad Razak',
      description: 'Permohonan bungkusan makanan raya untuk keluarga besar.',
      status: 'disbursing',
      priority: 'normal',
      category: 'zakat',
      amount: 500,
      memberId: members[1].id,
      programmeId: programmes[0].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 80,
      welfareScore: 83,
      createdAt: new Date('2024-08-01'),
    },
    {
      caseNumber: 'CS-0007',
      title: 'Permohonan bantuan keluarga Nurul Aini',
      description: 'Surirumah dengan anak kecil memerlukan bantuan bulanan.',
      status: 'verifying',
      priority: 'normal',
      category: 'zakat',
      amount: 1000,
      memberId: members[4].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      createdAt: new Date('2024-09-10'),
    },
    {
      caseNumber: 'CS-0008',
      title: 'Bantuan pendidikan anak-anak Abdul Rahman',
      description: 'Permohonan untuk 4 orang anak yang masih bersekolah.',
      status: 'submitted',
      priority: 'high',
      category: 'wakaf',
      amount: 4000,
      memberId: members[13].id,
      programmeId: programmes[1].id,
      creatorId: admin.id,
      createdAt: new Date('2024-10-01'),
    },
    {
      caseNumber: 'CS-0009',
      title: 'Bantuan untuk mangsa banjir Khalid',
      description: 'Bantuan kecemasan akibat banjir di kawasan Gombak.',
      status: 'draft',
      priority: 'urgent',
      category: 'infak',
      amount: 800,
      memberId: members[11].id,
      programmeId: programmes[6].id,
      creatorId: admin.id,
      createdAt: new Date('2024-11-15'),
    },
    {
      caseNumber: 'CS-0010',
      title: 'Permohonan Raju a/l Supramaniam',
      description: 'Muallaf baru memohon bantuan pemulihan dan sokongan.',
      status: 'scoring',
      priority: 'normal',
      category: 'sedekah',
      amount: 1500,
      memberId: members[7].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 76,
      createdAt: new Date('2024-11-20'),
    },
    {
      caseNumber: 'CS-0011',
      title: 'Bantuan warga emas Osman',
      description: 'Warga emas bersendirian memerlukan bantuan makanan asas.',
      status: 'verified',
      priority: 'normal',
      category: 'zakat',
      amount: 600,
      memberId: members[9].id,
      programmeId: programmes[0].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 90,
      welfareScore: 88,
      createdAt: new Date('2024-12-01'),
    },
    {
      caseNumber: 'CS-0012',
      title: 'Permohonan Rosnah keluarga besar',
      description:
        'Isteri kepada pekerja yang tercedera memerlukan bantuan segera.',
      status: 'rejected',
      priority: 'high',
      category: 'government_aid',
      amount: 2000,
      memberId: members[10].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 45,
      welfareScore: 50,
      notes: 'Ditolak - dokumen tidak lengkap. Boleh memohon semula.',
      createdAt: new Date('2024-12-05'),
    },
    {
      caseNumber: 'CS-0013',
      title: 'Bantuan kesihatan Mastura',
      description: 'Anak bongsu memerlukan rawatan khas di hospital.',
      status: 'approved',
      priority: 'urgent',
      category: 'zakat',
      amount: 5000,
      memberId: members[14].id,
      programmeId: programmes[3].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 94,
      welfareScore: 96,
      createdAt: new Date('2025-01-05'),
    },
    {
      caseNumber: 'CS-0014',
      title: 'Bantuan Aminah warga emas',
      description: 'Pesara menjaga anak OKU memerlukan sokongan.',
      status: 'disbursed',
      priority: 'normal',
      category: 'sedekah',
      amount: 1800,
      memberId: members[6].id,
      programmeId: programmes[4].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 87,
      welfareScore: 85,
      createdAt: new Date('2025-01-10'),
    },
    {
      caseNumber: 'CS-0015',
      title: 'Permohonan bantuan makanan Halimah',
      description: 'Permohonan bantuan makanan bulanan. Menunggu pemindahan.',
      status: 'follow_up',
      priority: 'low',
      category: 'infak',
      amount: 400,
      memberId: members[12].id,
      programmeId: programmes[0].id,
      creatorId: admin.id,
      assigneeId: admin.id,
      verificationScore: 65,
      welfareScore: 70,
      createdAt: new Date('2025-01-15'),
    },
  ]

  const cases = []
  for (const c of casesData) {
    cases.push(await db.case.create({ data: c }))
  }
  console.log(`✅ Cases created: ${cases.length} records`)

  // ============================================================
  // 8. DONATIONS - 20 donations, total ~RM 150,000
  // ============================================================
  const donationsData = [
    {
      donationNumber: 'DN-0001',
      donorName: 'Syarikat Tenaga Sdn Bhd',
      donorIC: null,
      donorEmail: 'csr@tenaga.com.my',
      donorPhone: '03-2200 1234',
      amount: 25000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'CSR Program',
      fundType: 'zakat',
      zakatCategory: 'pendapatan',
      zakatAuthority: 'LZNK',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-001',
      programmeId: programmes[4].id,
      notes: 'Derma tahunan melalui program CSR',
      donatedAt: new Date('2024-01-15'),
    },
    {
      donationNumber: 'DN-0002',
      donorName: 'Haji Ali bin Abu Bakar',
      donorIC: '550101-01-5234',
      donorEmail: null,
      donorPhone: '013-234 5678',
      amount: 10000,
      status: 'confirmed',
      method: 'online',
      channel: 'Website',
      fundType: 'zakat',
      zakatCategory: 'harta',
      zakatAuthority: 'LZNK',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-002',
      programmeId: programmes[4].id,
      notes: 'Zakat harta tahunan',
      donatedAt: new Date('2024-02-10'),
    },
    {
      donationNumber: 'DN-0003',
      donorName: 'Penderma Tanpa Nama',
      donorIC: null,
      donorEmail: null,
      donorPhone: null,
      amount: 5000,
      status: 'confirmed',
      method: 'cash',
      channel: 'Kaunter PUSPA',
      fundType: 'sadaqah',
      shariahCompliant: true,
      isAnonymous: true,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-003',
      programmeId: programmes[0].id,
      notes: 'Sedekah tunai melalui kotak derma',
      donatedAt: new Date('2024-03-05'),
    },
    {
      donationNumber: 'DN-0004',
      donorName: 'Yayasan Hasanah',
      donorIC: null,
      donorEmail: 'grant@yayasanhasanah.org',
      donorPhone: '03-2712 3456',
      amount: 30000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'Pemindahan bank',
      fundType: 'waqf',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-004',
      programmeId: programmes[1].id,
      notes: 'Geran untuk tabung pendidikan anak asnaf',
      donatedAt: new Date('2024-03-20'),
    },
    {
      donationNumber: 'DN-0005',
      donorName: 'Puan Siti Aminah binti Hassan',
      donorIC: '650408-10-5432',
      donorEmail: 'siti.aminah@email.com',
      donorPhone: '012-345 6780',
      amount: 2000,
      status: 'confirmed',
      method: 'online',
      channel: 'Website',
      fundType: 'sadaqah',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-005',
      programmeId: programmes[3].id,
      notes: 'Sedekah untuk program kesihatan komuniti',
      donatedAt: new Date('2024-04-12'),
    },
    {
      donationNumber: 'DN-0006',
      donorName: 'Kumpulan Perusahaan Maju Bhd',
      donorIC: null,
      donorEmail: 'finance@perusahaan.com.my',
      donorPhone: '03-8800 9900',
      amount: 15000,
      status: 'confirmed',
      method: 'cheque',
      channel: 'Pos',
      fundType: 'infaq',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-006',
      programmeId: programmes[2].id,
      notes: 'Infaq untuk program latihan kemahiran',
      donatedAt: new Date('2024-05-08'),
    },
    {
      donationNumber: 'DN-0007',
      donorName: 'Encik Mohd Razif bin Ismail',
      donorIC: '780912-01-5678',
      donorEmail: 'razif@email.com',
      donorPhone: '017-234 5678',
      amount: 500,
      status: 'confirmed',
      method: 'ewallet',
      channel: 'DuitNow',
      fundType: 'donation_general',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-007',
      notes: 'Derma melalui DuitNow',
      donatedAt: new Date('2024-05-20'),
    },
    {
      donationNumber: 'DN-0008',
      donorName: 'Masjid Al-Ikhlas Hulu Klang',
      donorIC: null,
      donorEmail: null,
      donorPhone: '03-4108 1234',
      amount: 8000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'Pemindahan bank',
      fundType: 'zakat',
      zakatCategory: 'fitrah',
      zakatAuthority: 'LZNK',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-008',
      programmeId: programmes[4].id,
      notes: 'Tabung zakat fitrah dari masjid',
      donatedAt: new Date('2024-06-01'),
    },
    {
      donationNumber: 'DN-0009',
      donorName: 'Penderma Wellwisher',
      donorIC: null,
      donorEmail: null,
      donorPhone: null,
      amount: 3000,
      status: 'confirmed',
      method: 'online',
      channel: 'Website',
      fundType: 'donation_general',
      shariahCompliant: true,
      isAnonymous: true,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-009',
      programmeId: programmes[0].id,
      notes: 'Derma dalam talian tanpa nama',
      donatedAt: new Date('2024-06-15'),
    },
    {
      donationNumber: 'DN-0010',
      donorName: 'Encik Tan Kim Hock',
      donorIC: '700315-14-5234',
      donorEmail: 'tankh@email.com',
      donorPhone: '016-567 8901',
      amount: 10000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'Pemindahan bank',
      fundType: 'sadaqah',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-010',
      programmeId: programmes[3].id,
      notes: 'Sedekah dari rakan komuniti bukan Islam',
      donatedAt: new Date('2024-07-10'),
    },
    {
      donationNumber: 'DN-0011',
      donorName: 'Jemaah Masjid Jamek Ampang',
      donorIC: null,
      donorEmail: null,
      donorPhone: '03-4296 5678',
      amount: 6500,
      status: 'confirmed',
      method: 'cash',
      channel: 'Kutipan masjid',
      fundType: 'zakat',
      zakatCategory: 'fitrah',
      zakatAuthority: 'LZNK',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-011',
      programmeId: programmes[0].id,
      notes: 'Kutipan zakat fitrah sempena Ramadhan',
      donatedAt: new Date('2024-07-20'),
    },
    {
      donationNumber: 'DN-0012',
      donorName: 'Puan Hajah Salwani binti Hussin',
      donorIC: '600801-06-5123',
      donorEmail: 'salwani@email.com',
      donorPhone: '013-890 1234',
      amount: 7500,
      status: 'confirmed',
      method: 'online',
      channel: 'Website',
      fundType: 'waqf',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-012',
      programmeId: programmes[1].id,
      notes: 'Wakaf pendidikan untuk anak yatim',
      donatedAt: new Date('2024-08-05'),
    },
    {
      donationNumber: 'DN-0013',
      donorName: 'Bank Muamalat Malaysia',
      donorIC: null,
      donorEmail: 'csr@muamalat.com.my',
      donorPhone: '03-2600 0000',
      amount: 12000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'CSR Program',
      fundType: 'infaq',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-013',
      programmeId: programmes[6].id,
      notes: 'Infaq untuk tabung kecemasan banjir',
      donatedAt: new Date('2024-09-01'),
    },
    {
      donationNumber: 'DN-0014',
      donorName: 'Encik Ahmad Faizal bin Norizan',
      donorIC: '850301-01-5678',
      donorEmail: 'faizal.n@email.com',
      donorPhone: '018-234 5678',
      amount: 1000,
      status: 'confirmed',
      method: 'ewallet',
      channel: 'Touch n Go',
      fundType: 'donation_general',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-014',
      notes: 'Derma melalui Touch n Go eWallet',
      donatedAt: new Date('2024-09-15'),
    },
    {
      donationNumber: 'DN-0015',
      donorName: 'Koperasi Bangsa Bhd',
      donorIC: null,
      donorEmail: 'admin@kopbangsa.com',
      donorPhone: '03-5510 1234',
      amount: 5500,
      status: 'confirmed',
      method: 'cheque',
      channel: 'Pos',
      fundType: 'sadaqah',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2024-015',
      programmeId: programmes[4].id,
      notes: 'Derma dari koperasi untuk bantuan bulanan',
      donatedAt: new Date('2024-10-10'),
    },
    {
      donationNumber: 'DN-0016',
      donorName: 'Dr. Nurul Syuhada binti Mohd Noor',
      donorIC: '820615-02-5432',
      donorEmail: 'nurul.syuhada@email.com',
      donorPhone: '012-456 7890',
      amount: 800,
      status: 'confirmed',
      method: 'online',
      channel: 'Website',
      fundType: 'donation_general',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-016',
      programmeId: programmes[7].id,
      notes: 'Derma untuk kelas dakwah bulanan',
      donatedAt: new Date('2024-10-25'),
    },
    {
      donationNumber: 'DN-0017',
      donorName: 'Majlis Agama Islam Wilayah Persekutuan',
      donorIC: null,
      donorEmail: 'zakat@maiwp.gov.my',
      donorPhone: '03-2274 8841',
      amount: 2000,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'Pemindahan bank',
      fundType: 'zakat',
      zakatCategory: 'perniagaan',
      zakatAuthority: 'MAIWP',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      receiptNumber: 'RCP-2024-017',
      programmeId: programmes[4].id,
      notes: 'Agihan zakat dari MAIWP',
      donatedAt: new Date('2024-11-05'),
    },
    {
      donationNumber: 'DN-0018',
      donorName: 'Encik Muhammad Amin bin Hamid',
      donorIC: '900423-01-5987',
      donorEmail: null,
      donorPhone: '019-876 5432',
      amount: 200,
      status: 'pending',
      method: 'cash',
      channel: 'Kaunter PUSPA',
      fundType: 'donation_general',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      notes: 'Menunggu pengesahan kaunter',
      donatedAt: new Date('2025-01-02'),
    },
    {
      donationNumber: 'DN-0019',
      donorName: 'Puan Rogayah binti Che Mat',
      donorIC: '720810-02-5432',
      donorEmail: 'rogayah@email.com',
      donorPhone: '014-345 6789',
      amount: 1500,
      status: 'failed',
      method: 'online',
      channel: 'Website',
      fundType: 'sadaqah',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: false,
      notes: 'Pemindahan gagal - rujukan bank pendonor',
      donatedAt: new Date('2025-01-05'),
    },
    {
      donationNumber: 'DN-0020',
      donorName: 'Syarikat Pembinaan Setia Bhd',
      donorIC: null,
      donorEmail: 'csr@setiabina.com.my',
      donorPhone: '03-7890 1234',
      amount: 3500,
      status: 'confirmed',
      method: 'bank_transfer',
      channel: 'CSR Program',
      fundType: 'infaq',
      shariahCompliant: true,
      isAnonymous: false,
      isTaxDeductible: true,
      receiptNumber: 'RCP-2025-001',
      programmeId: programmes[5].id,
      notes: 'Infaq untuk program gotong-royong komuniti',
      donatedAt: new Date('2025-01-10'),
    },
  ]

  const donations = []
  for (const d of donationsData) {
    donations.push(await db.donation.create({ data: d }))
  }

  const totalDonations = donations
    .filter((d) => d.status === 'confirmed')
    .reduce((sum, d) => sum + d.amount, 0)
  console.log(
    `✅ Donations created: ${donations.length} records (confirmed total: RM ${totalDonations.toLocaleString()})`
  )

  // ============================================================
  // 9. DISBURSEMENTS - 12 disbursements
  // ============================================================
  const disbursementsData = [
    {
      disbursementNumber: 'DB-0001',
      amount: 1500,
      purpose: 'Bantuan zakat bulanan - Fatimah binti Osman',
      status: 'completed',
      recipientName: 'Fatimah binti Osman',
      recipientIC: '620315-07-5452',
      recipientBank: 'Maybank Islamic',
      recipientAcc: '1142 2233 4455',
      scheduledDate: new Date('2024-04-01'),
      processedDate: new Date('2024-04-01'),
      approvedBy: admin.id,
      caseId: cases[0].id,
      programmeId: programmes[4].id,
      memberId: members[0].id,
      notes: 'Bayaran penuh. Kes telah ditutup.',
    },
    {
      disbursementNumber: 'DB-0002',
      amount: 3000,
      purpose: 'Tabung pendidikan - Siti Hajar binti Kamal',
      status: 'completed',
      recipientName: 'Siti Hajar binti Kamal',
      recipientIC: '950412-06-5432',
      recipientBank: 'Bank Islam',
      recipientAcc: '2233 4455 6677',
      scheduledDate: new Date('2024-05-01'),
      processedDate: new Date('2024-05-02'),
      approvedBy: admin.id,
      caseId: cases[1].id,
      programmeId: programmes[1].id,
      memberId: members[8].id,
    },
    {
      disbursementNumber: 'DB-0003',
      amount: 2000,
      purpose: 'Bantuan perubatan - Zaiton binti Mamat',
      status: 'approved',
      recipientName: 'Zaiton binti Mamat',
      recipientIC: '850610-10-5084',
      recipientBank: 'CIMB Islamic',
      recipientAcc: '5566 7788 9900',
      scheduledDate: new Date('2025-02-01'),
      approvedBy: admin.id,
      caseId: cases[2].id,
      programmeId: programmes[3].id,
      memberId: members[2].id,
      notes: 'Menunggu tarikh jadual bayaran.',
    },
    {
      disbursementNumber: 'DB-0004',
      amount: 500,
      purpose: 'Bungkusan makanan raya - Ahmad bin Razak',
      status: 'processing',
      recipientName: 'Ahmad bin Razak',
      recipientIC: '780422-01-5731',
      recipientBank: 'Bank Islam',
      recipientAcc: '1142 3344 5566',
      scheduledDate: new Date('2025-01-20'),
      approvedBy: admin.id,
      caseId: cases[5].id,
      programmeId: programmes[0].id,
      memberId: members[1].id,
    },
    {
      disbursementNumber: 'DB-0005',
      amount: 1800,
      purpose: 'Bantuan bulanan 6 bulan - Aminah binti Hashim',
      status: 'completed',
      recipientName: 'Aminah binti Hashim',
      recipientIC: '700718-08-5678',
      recipientBank: 'Maybank Islamic',
      recipientAcc: '3344 5566 7788',
      scheduledDate: new Date('2025-01-15'),
      processedDate: new Date('2025-01-15'),
      approvedBy: admin.id,
      caseId: cases[13].id,
      programmeId: programmes[4].id,
      memberId: members[6].id,
    },
    {
      disbursementNumber: 'DB-0006',
      amount: 22450,
      purpose: 'Program Bantuan Makanan Raya - keseluruhan',
      status: 'completed',
      recipientName: 'Pelbagai penerima asnaf',
      recipientBank: null,
      recipientAcc: null,
      scheduledDate: new Date('2024-04-05'),
      processedDate: new Date('2024-04-05'),
      approvedBy: admin.id,
      programmeId: programmes[0].id,
      notes: 'Perbelanjaan keseluruhan program makanan raya.',
    },
    {
      disbursementNumber: 'DB-0007',
      amount: 11200,
      purpose: 'Klinik Kesihatan Komuniti - peralatan & ubatan',
      status: 'completed',
      recipientName: 'Pembekal ubatan & peralatan',
      recipientBank: 'Maybank Islamic',
      recipientAcc: '5621 7890 3456',
      scheduledDate: new Date('2024-09-01'),
      processedDate: new Date('2024-09-01'),
      approvedBy: admin.id,
      programmeId: programmes[3].id,
    },
    {
      disbursementNumber: 'DB-0008',
      amount: 1200,
      purpose: 'Bantuan bulanan Ismail bin Md Noor (3 bulan)',
      status: 'pending',
      recipientName: 'Ismail bin Md Noor',
      recipientIC: '600923-01-5234',
      recipientBank: 'Bank Rakyat',
      recipientAcc: '4455 6677 8899',
      scheduledDate: new Date('2025-02-01'),
      approvedBy: admin.id,
      caseId: cases[3].id,
      programmeId: programmes[4].id,
      memberId: members[5].id,
    },
    {
      disbursementNumber: 'DB-0009',
      amount: 500,
      purpose: 'Bantuan latihan ICT - Mohd Faisal bin Ismail',
      status: 'pending',
      recipientName: 'Mohd Faisal bin Ismail',
      recipientIC: '900501-01-6123',
      scheduledDate: new Date('2025-03-01'),
      caseId: cases[4].id,
      programmeId: programmes[2].id,
      memberId: members[3].id,
      notes: 'Program belum bermula. Menunggu pelancaran.',
    },
    {
      disbursementNumber: 'DB-0010',
      amount: 4800,
      purpose: 'Gotong-Royong Komuniti - perbelanjaan',
      status: 'completed',
      recipientName: 'Pembekal & kontraktor',
      scheduledDate: new Date('2024-05-15'),
      processedDate: new Date('2024-05-15'),
      approvedBy: admin.id,
      programmeId: programmes[5].id,
    },
    {
      disbursementNumber: 'DB-0011',
      amount: 5000,
      purpose: 'Bantuan kewangan - Mastura binti Yahya',
      status: 'failed',
      recipientName: 'Mastura binti Yahya',
      recipientIC: '880512-03-5789',
      recipientBank: 'Maybank Islamic',
      recipientAcc: '7623 4455 6677',
      scheduledDate: new Date('2025-01-20'),
      approvedBy: admin.id,
      caseId: cases[12].id,
      programmeId: programmes[3].id,
      memberId: members[14].id,
      notes: 'Gagal - nombor akaun tidak sah. Menunggu maklumat baru.',
    },
    {
      disbursementNumber: 'DB-0012',
      amount: 1000,
      purpose: 'Bantuan awal pendaftaran Nurul Aini',
      status: 'cancelled',
      recipientName: 'Nurul Aini binti Abdullah',
      recipientIC: '920815-03-5847',
      scheduledDate: new Date('2025-02-01'),
      caseId: cases[6].id,
      programmeId: programmes[4].id,
      memberId: members[4].id,
      notes: 'Dibatalkan - permohonan masih dalam pengesahan.',
    },
  ]

  const disbursements = []
  for (const d of disbursementsData) {
    disbursements.push(await db.disbursement.create({ data: d }))
  }
  console.log(`✅ Disbursements created: ${disbursements.length} records`)

  // ============================================================
  // 10. ACTIVITIES - 10 activities across 4 kanban columns
  // ============================================================
  const activitiesData = [
    {
      title: 'Sesi pendaftaran asnaf baharu - Q1 2025',
      description:
        'Menganjurkan sesi pendaftaran terbuka untuk asnaf baharu di kawasan Hulu Klang.',
      type: 'event',
      status: 'planned',
      date: new Date('2025-02-15'),
      endDate: new Date('2025-02-15'),
      location: 'Pejabat PUSPA',
      programmeId: programmes[4].id,
      assignees: JSON.stringify(['Pentadbir PUSPA', 'Encik Kamal bin Zainal']),
      notes: 'Sediakan borang pendaftaran dan salinan IC.',
      order: 0,
    },
    {
      title: 'Latihan kemahiran ICT - Fasa 1',
      description:
        'Modul asas komputer dan internet untuk 50 peserta.',
      type: 'task',
      status: 'planned',
      date: new Date('2025-03-01'),
      endDate: new Date('2025-03-31'),
      location: 'Pusat Komuniti Hulu Klang',
      programmeId: programmes[2].id,
      assignees: JSON.stringify(['Pentadbir PUSPA']),
      notes: 'Perlu sediakan 10 unit komputer.',
      order: 1,
    },
    {
      title: 'Lawatan rumah asnaf Fatimah',
      description:
        'Lawatan susulan untuk menilai keperluan semasa keluarga.',
      type: 'fieldwork',
      status: 'in_progress',
      date: new Date('2025-01-20'),
      location: 'Taman Sri Hulu Klang',
      assignees: JSON.stringify(['Pentadbir PUSPA']),
      notes: 'Bawa bungkusan makanan.',
      order: 0,
    },
    {
      title: 'Persediaan laporan tahunan 2024',
      description:
        'Menyusun data kewangan dan impak untuk laporan tahunan.',
      type: 'task',
      status: 'in_progress',
      date: new Date('2025-01-10'),
      endDate: new Date('2025-02-28'),
      assignees: JSON.stringify([
        'Pentadbir PUSPA',
        'Puan Noraini binti Omar',
      ]),
      notes: 'Mesti siap sebelum mesyuarat AGM Mac 2025.',
      order: 1,
    },
    {
      title: 'Mesyuarat jawatankuasa bulanan - Januari',
      description:
        'Mesyuarat bulanan untuk membincangkan kemajuan program dan hal semasa.',
      type: 'meeting',
      status: 'completed',
      date: new Date('2025-01-10'),
      endDate: new Date('2025-01-10'),
      location: 'Bilik mesyuarat PUSPA',
      assignees: JSON.stringify([
        'Haji Ahmad bin Ismail',
        'Dr. Siti Aminah binti Hassan',
        'Pentadbir PUSPA',
      ]),
      notes: 'Keputusan: meluluskan bajet Q1 2025.',
      order: 0,
    },
    {
      title: 'Program edaran makanan raya 2024',
      description:
        'Edaran 200 bungkusan makanan dan wang raya kepada asnaf.',
      type: 'event',
      status: 'completed',
      date: new Date('2024-04-05'),
      endDate: new Date('2024-04-06'),
      location: 'Masjid Al-Ikhlas Hulu Klang',
      programmeId: programmes[0].id,
      assignees: JSON.stringify([
        'Pentadbir PUSPA',
        'Ustaz Muhammad bin Abdullah',
        'Sukarelawan',
      ]),
      notes: 'Berjaya edar 178 bungkusan. 22 tunggilan perlu dijadualkan semula.',
      order: 1,
    },
    {
      title: 'Gotong-Royong Komuniti Taman Sri Hulu Klang',
      description:
        'Program kebersihan bersama penduduk setempat.',
      type: 'event',
      status: 'completed',
      date: new Date('2024-05-15'),
      endDate: new Date('2024-05-15'),
      location: 'Taman Sri Hulu Klang',
      programmeId: programmes[5].id,
      assignees: JSON.stringify([
        'Pentadbir PUSPA',
        'Encik Rizal bin Hamid',
        'Majlis Perbandaran Ampang',
      ]),
      notes: '85 peserta. Berjaya membersih 3 kawasan.',
      order: 2,
    },
    {
      title: 'Klinik kesihatan komuniti - Disember 2024',
      description: 'Sesi pemeriksaan kesihatan percuma bulanan.',
      type: 'event',
      status: 'completed',
      date: new Date('2024-12-15'),
      endDate: new Date('2024-12-15'),
      location: 'Masjid Nurul Hidayah Keramat',
      programmeId: programmes[3].id,
      assignees: JSON.stringify(['Pentadbir PUSPA', 'Dr. Lim Wei Ling']),
      notes: '45 peserta diperiksa.',
      order: 3,
    },
    {
      title: 'Pertandingan poster dakwah (dibatalkan)',
      description:
        'Pertandingan poster dakwah untuk belia (dibatalkan kerana kekurangan penyertaan).',
      type: 'event',
      status: 'cancelled',
      date: new Date('2024-11-01'),
      location: 'Pejabat PUSPA',
      programmeId: programmes[7].id,
      notes: 'Dibatalkan - hanya 3 penyertaan diterima.',
      order: 0,
    },
    {
      title: 'Kempen derma awam di pasar malam',
      description:
        'Menyediakan booth derma di pasar malam Hulu Klang.',
      type: 'event',
      status: 'planned',
      date: new Date('2025-03-20'),
      endDate: new Date('2025-03-20'),
      location: 'Pasar Malam Hulu Klang',
      assignees: JSON.stringify(['Pentadbir PUSPA', 'Puan Aishah binti Yusof']),
      notes: 'Perlu kebenaran penganjur pasar malam.',
      order: 2,
    },
  ]

  const activities = []
  for (const a of activitiesData) {
    activities.push(await db.activity.create({ data: a }))
  }
  console.log(`✅ Activities created: ${activities.length} records`)

  // ============================================================
  // 11. IMPACT METRICS - 8 metrics linked to programmes
  // ============================================================
  const impactMetricsData = [
    {
      programmeId: programmes[0].id,
      metricName: 'Jumlah penerima makanan raya',
      description: 'Bilangan individu yang menerima bungkusan makanan raya',
      selfReportedValue: 200,
      verifiedValue: 178,
      verificationSource: 'Borang pengedaran ditandatangani penerima',
      verificationDate: new Date('2024-04-10'),
      methodology: 'Kiraan borang yang ditandatangani semasa edaran',
      period: '2024',
    },
    {
      programmeId: programmes[1].id,
      metricName: 'Pelajar yang menerima bantuan pendidikan',
      description: 'Bilangan pelajar yang menerima wang bantuan pendidikan',
      selfReportedValue: 70,
      verifiedValue: 67,
      verificationSource: 'Resit pembayaran yuran',
      verificationDate: new Date('2024-12-15'),
      methodology: 'Berdasarkan resit pembayaran yuran yang diserahkan',
      period: '2024',
    },
    {
      programmeId: programmes[1].id,
      metricName: 'Wang pendidikan diagihkan (RM)',
      description: 'Jumlah wang diagihkan untuk pendidikan',
      selfReportedValue: 35000,
      verifiedValue: 33500,
      verificationSource: 'Penyata bank',
      verificationDate: new Date('2024-12-31'),
      methodology: 'Jumlah pemindahan bank yang disahkan',
      period: '2024',
    },
    {
      programmeId: programmes[3].id,
      metricName: 'Pesakit diperiksa di klinik komuniti',
      description: 'Bilangan pesakit yang menjalani pemeriksaan kesihatan',
      selfReportedValue: 250,
      verifiedValue: 245,
      verificationSource: 'Daftar hadir klinik',
      verificationDate: new Date('2024-12-31'),
      methodology: 'Berdasarkan daftar hadir pesakit',
      period: '2024',
    },
    {
      programmeId: programmes[3].id,
      metricName: 'Kadar kawalan penyakit kronik (%)',
      description: 'Peratus pesakit kronik yang mencapai sasaran rawatan',
      selfReportedValue: 75,
      verifiedValue: null,
      verificationSource: null,
      methodology: 'Data laporan doktor rakan kongsi KKM',
      period: '2024',
    },
    {
      programmeId: programmes[4].id,
      metricName: 'Penerima bantuan bulanan aktif',
      description: 'Bilangan penerima bantuan kewangan bulanan aktif',
      selfReportedValue: 65,
      verifiedValue: 62,
      verificationSource: 'Senarai semak pengesahan bulanan',
      verificationDate: new Date('2024-12-31'),
      methodology: 'Bilangan penerima yang menerima sekurang-kurangnya 10 bulan',
      period: '2024',
    },
    {
      programmeId: programmes[4].id,
      metricName: 'Jumlah bantuan bulanan diagihkan (RM)',
      description: 'Jumlah wang bantuan bulanan yang diagihkan',
      selfReportedValue: 75000,
      verifiedValue: 74400,
      verificationSource: 'Penyata bank',
      verificationDate: new Date('2024-12-31'),
      methodology: 'Jumlah pemindahan bank berdasarkan penyata',
      period: '2024',
    },
    {
      programmeId: programmes[7].id,
      metricName: 'Peserta kelas dakwah bulanan',
      description: 'Bilangan peserta tetap kelas dakwah',
      selfReportedValue: 50,
      verifiedValue: 48,
      verificationSource: 'Daftar hadir',
      verificationDate: new Date('2024-12-31'),
      methodology: 'Bilangan peserta yang hadir sekurang-kurangnya 8 sesi setahun',
      period: '2024',
    },
  ]

  const impactMetrics = []
  for (const im of impactMetricsData) {
    impactMetrics.push(await db.impactMetric.create({ data: im }))
  }
  console.log(`✅ ImpactMetrics created: ${impactMetrics.length} records`)

  // ============================================================
  // 12. COMPLIANCE CHECKLIST - 16 items (9 completed, 7 incomplete = 56%)
  // ============================================================
  const complianceData = [
    // Registration (4 items, 3 completed)
    {
      category: 'registration',
      item: 'Pendaftaran ROS / PPM',
      description: 'Sijil pendaftaran dengan Pendaftar Pertubuhan Malaysia',
      isCompleted: true,
      completedAt: new Date('2020-03-14'),
      evidenceUrl: '/documents/ros-cert.pdf',
      notes: 'PPM-006-14-14032020',
      order: 1,
    },
    {
      category: 'registration',
      item: 'Pemastautin pejabat',
      description: 'Alamat pejabat berdaftar dan dikemas kini',
      isCompleted: true,
      completedAt: new Date('2020-05-01'),
      evidenceUrl: '/documents/office-address.pdf',
      order: 2,
    },
    {
      category: 'registration',
      item: 'Surat kuasa pejabat',
      description: 'Surat persetujuan pemilik premis pejabat',
      isCompleted: false,
      notes: 'Perlu diperbaharui setiap tahun',
      order: 3,
    },
    {
      category: 'registration',
      item: 'Lesen perniagaan / operasi',
      description: 'Lesen operasi PBT yang sah',
      isCompleted: true,
      completedAt: new Date('2024-01-15'),
      evidenceUrl: '/documents/license-2024.pdf',
      order: 4,
    },
    // Governance (4 items, 2 completed)
    {
      category: 'governance',
      item: 'Perlembagaan pertubuhan',
      description: 'Perlembagaan yang diluluskan dan dikemas kini',
      isCompleted: true,
      completedAt: new Date('2020-03-14'),
      evidenceUrl: '/documents/constitution.pdf',
      order: 5,
    },
    {
      category: 'governance',
      item: 'Mesyuarat AGM tahunan',
      description: 'Mesyuarat tahunan diadakan sekurang-kurangnya sekali setahun',
      isCompleted: true,
      completedAt: new Date('2024-03-20'),
      evidenceUrl: '/documents/agm-minutes-2024.pdf',
      notes: 'AGM terakhir diadakan pada 20 Mac 2024',
      order: 6,
    },
    {
      category: 'governance',
      item: 'Senarai jawatankuasa terkini',
      description: 'Senarai AJK yang dikemas kini dan diserahkan kepada ROS',
      isCompleted: false,
      notes: 'Perlu diserahkan selepas pelantikan AJK Jan 2024',
      order: 7,
    },
    {
      category: 'governance',
      item: 'Polisi perlindungan data',
      description: 'Polisi perlindungan data peribadi penerima dan penderma',
      isCompleted: false,
      notes: 'Sedang disediakan',
      order: 8,
    },
    // Financial (4 items, 2 completed)
    {
      category: 'financial',
      item: 'Akaun bank berdaftar',
      description: 'Akaun bank pertubuhan atas nama pertubuhan',
      isCompleted: true,
      completedAt: new Date('2020-04-01'),
      evidenceUrl: '/documents/bank-verification.pdf',
      notes: 'Maybank Islamic - 5621 7890 3456',
      order: 9,
    },
    {
      category: 'financial',
      item: 'Penyata kewangan diaudit',
      description: 'Penyata kewangan tahunan yang diaudit',
      isCompleted: false,
      notes: 'Sedang menunggu firma audit menyelesaikan laporan 2024',
      order: 10,
    },
    {
      category: 'financial',
      item: 'Kelulusan LHDN (pengecualian cukai)',
      description: 'Kelulusan LHDN untuk pengecualian cukai penderma',
      isCompleted: true,
      completedAt: new Date('2021-06-15'),
      evidenceUrl: '/documents/lhdn-approval.pdf',
      notes: 'LHDN.01/35/42/179/2021 - tamat 31 Dis 2026',
      order: 11,
    },
    {
      category: 'financial',
      item: 'Polisi pendermaan',
      description: 'Polisi penerimaan dan pengurusan derma',
      isCompleted: false,
      notes: 'Perlu dimuktamadkan oleh Bendahari',
      order: 12,
    },
    // Programme (2 items, 1 completed)
    {
      category: 'programme',
      item: 'Laporan program tahunan',
      description: 'Laporan pelaksanaan dan impak program',
      isCompleted: false,
      notes: 'Sedang disediakan untuk 2024',
      order: 13,
    },
    {
      category: 'programme',
      item: 'Kriteria kelayakan asnaf',
      description: 'Kriteria kelayakan penerima bantuan yang ditetapkan dan didokumenkan',
      isCompleted: true,
      completedAt: new Date('2023-06-01'),
      evidenceUrl: '/documents/asnaf-criteria.pdf',
      order: 14,
    },
    // Transparency (2 items, 1 completed)
    {
      category: 'transparency',
      item: 'Laman web dikemas kini',
      description: 'Maklumat pertubuhan terkini di laman web',
      isCompleted: false,
      notes: 'Perlu dikemas kini profil AJK dan laporan kewangan',
      order: 15,
    },
    {
      category: 'transparency',
      item: 'Salinan resit untuk penderma',
      description: 'Resit rasmi dikeluarkan untuk semua derma',
      isCompleted: true,
      completedAt: new Date('2023-01-01'),
      notes: 'Sistem resit automatik melalui sistem PUSPA',
      order: 16,
    },
  ]

  const complianceItems = []
  for (const c of complianceData) {
    complianceItems.push(await db.complianceChecklist.create({ data: c }))
  }
  const completedCount = complianceItems.filter((c) => c.isCompleted).length
  const complianceScore = Math.round((completedCount / complianceItems.length) * 100)
  console.log(
    `✅ ComplianceChecklist created: ${complianceItems.length} records (${completedCount}/${complianceItems.length} = ${complianceScore}%)`
  )

  // ============================================================
  // 13. PUBLIC REPORTS - 2 draft reports
  // ============================================================
  const publicReports = await db.publicReport.createMany({
    data: [
      {
        title: 'Laporan Tahunan PUSPA 2024',
        type: 'annual',
        year: '2024',
        period: '2024',
        url: null,
        status: 'draft',
      },
      {
        title: 'Laporan Kewangan Audit 2024',
        type: 'financial',
        year: '2024',
        period: '2024',
        url: null,
        status: 'draft',
      },
    ],
  })
  console.log(`✅ PublicReports created: ${publicReports.count} records`)

  // ============================================================
  // 14. AUDIT LOGS - 10 entries
  // ============================================================
  const auditLogs = await db.auditLog.createMany({
    data: [
      {
        action: 'login',
        entity: 'User',
        entityId: admin.id,
        details: '{"email": "admin@puspa.org.my"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T08:30:00'),
      },
      {
        action: 'create',
        entity: 'Member',
        details: '{"name": "Fatimah binti Osman", "memberNumber": "PUSPA-0001"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T09:00:00'),
      },
      {
        action: 'create',
        entity: 'Case',
        details: '{"title": "Bantuan zakat untuk keluarga Fatimah", "caseNumber": "CS-0001"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T09:30:00'),
      },
      {
        action: 'update',
        entity: 'Case',
        entityId: cases[0].id,
        details: '{"status": "draft → submitted", "caseNumber": "CS-0001"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T10:00:00'),
      },
      {
        action: 'create',
        entity: 'Donation',
        details: '{"donorName": "Syarikat Tenaga Sdn Bhd", "amount": 25000}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T11:00:00'),
      },
      {
        action: 'create',
        entity: 'Disbursement',
        details: '{"disbursementNumber": "DB-0001", "amount": 1500, "recipientName": "Fatimah binti Osman"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T14:00:00'),
      },
      {
        action: 'update',
        entity: 'Disbursement',
        entityId: disbursements[0].id,
        details: '{"status": "approved → completed", "disbursementNumber": "DB-0001"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-15T14:30:00'),
      },
      {
        action: 'export',
        entity: 'Donation',
        details: '{"period": "2024", "format": "xlsx"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-16T09:00:00'),
      },
      {
        action: 'create',
        entity: 'Programme',
        details: '{"name": "Latihan Kemahiran ICT", "category": "skills_training"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-16T10:30:00'),
      },
      {
        action: 'update',
        entity: 'OrganizationProfile',
        entityId: org.id,
        details: '{"field": "missionStatement", "action": "updated"}',
        userId: admin.id,
        ipAddress: '192.168.1.100',
        createdAt: new Date('2025-01-16T11:00:00'),
      },
    ],
  })
  console.log(`✅ AuditLogs created: ${auditLogs.count} records`)

  // ============================================================
  // 15. NOTIFICATIONS - 5 notifications
  // ============================================================
  const notifications = await db.notification.createMany({
    data: [
      {
        title: 'Selamat Datang ke Sistem PUSPA',
        message:
          'Akaun pentadbir anda telah berjaya didaftarkan. Sila tukar kata laluan anda sebaik sahaja log masuk.',
        type: 'info',
        isRead: true,
        userId: admin.id,
        link: '/settings',
        createdAt: new Date('2025-01-15T08:30:00'),
      },
      {
        title: 'Kes baru memerlukan pengesahan',
        message:
          'Kes CS-0007 (Permohonan bantuan keluarga Nurul Aini) sedang menunggu pengesahan dokumen.',
        type: 'warning',
        isRead: false,
        userId: admin.id,
        link: '/cases',
        createdAt: new Date('2025-01-15T10:00:00'),
      },
      {
        title: 'Pembayaran gagal',
        message:
          'Disbursement DB-0011 gagal diproses. Sila semak nombor akaun penerima Mastura binti Yahya.',
        type: 'error',
        isRead: false,
        userId: admin.id,
        link: '/disbursements',
        createdAt: new Date('2025-01-20T14:00:00'),
      },
      {
        title: 'Laporan tahunan perlu dikemas kini',
        message:
          'Sila sediakan draf laporan tahunan 2024 sebelum mesyuarat AGM pada bulan Mac.',
        type: 'info',
        isRead: false,
        userId: admin.id,
        link: '/reports',
        createdAt: new Date('2025-01-20T09:00:00'),
      },
      {
        title: 'Program Latihan ICT diluluskan',
        message:
          'Program Latihan Kemahiran ICT telah diluluskan dengan bajet RM 30,000. Tarikh mula: 1 Februari 2025.',
        type: 'success',
        isRead: true,
        userId: admin.id,
        link: '/programmes',
        createdAt: new Date('2025-01-16T10:30:00'),
      },
    ],
  })
  console.log(`✅ Notifications created: ${notifications.count} records`)

  // ============================================================
  // SUMMARY
  // ============================================================
  console.log('\n' + '='.repeat(60))
  console.log('📊 SEED SUMMARY - PUSPA NGO System')
  console.log('='.repeat(60))
  console.log(`  Organization Profile : 1`)
  console.log(`  Users               : 1 (admin)`)
  console.log(`  Board Members       : 7`)
  console.log(`  Partners            : 8 (5 masjid, 1 yayasan, 2 kerajaan)`)
  console.log(`  Members (Asnaf)     : 15`)
  console.log(`  Household Members   : ${householdMembers.count}`)
  console.log(`  Programmes          : 8`)
  console.log(`  Cases               : 15 (across 12 statuses)`)
  console.log(`  Donations           : 20 (confirmed: RM ${totalDonations.toLocaleString()})`)
  console.log(`  Disbursements       : 12`)
  console.log(`  Activities          : 10 (across 4 kanban columns)`)
  console.log(`  Impact Metrics      : 8`)
  console.log(`  Compliance Items    : 16 (${completedCount}/16 = ${complianceScore}%)`)
  console.log(`  Public Reports      : 2 (draft)`)
  console.log(`  Audit Logs          : 10`)
  console.log(`  Notifications       : 5`)
  console.log('='.repeat(60))
  console.log('✅ Seed completed successfully!\n')
}

main()
  .then(async () => {
    await db.$disconnect()
  })
  .catch(async (e) => {
    console.error('❌ Seed failed:', e)
    await db.$disconnect()
    process.exit(1)
  })
